INSERT INTO dofa_rubrics (section_name, sub_section, max_marks) VALUES 
('1. Teaching Feedback', 'If no. of students is greater than or equal to 50: Feedback>=4', 5),
('1. Teaching Feedback', 'If no. of students is greater than or equal to 50: 3.5<=Feedback<4', 4),
('1. Teaching Feedback', 'If no. of students is greater than or equal to 50: 3<=Feedback<3.5', 3),
('1. Teaching Feedback', 'If no. of students is less than 50: Feedback>=4', 4),
('1. Teaching Feedback', 'If no. of students is less than 50: 3.5<=Feedback<4', 3),
('1. Teaching Feedback', 'If no. of students is less than 50: 3<=Feedback<3.5', 2),

('2. Research Guidance', 'BTP (points for each project)', 2),
('2. Research Guidance', 'PhD guidance (points for each project)', 15),
('2. Research Guidance', 'Co-guide', 7.5),
('2. Research Guidance', 'M.Tech./M.Sc. Project guidance (points for each student)', 5),

('3. New Courses designed', 'New Courses designed', 4),

('4. Research publications', 'Journals: Q1', 10),
('4. Research publications', 'Journals: Q2', 8),
('4. Research publications', 'Journals: Q3', 6),
('4. Research publications', 'Journals: Q4/Scopus/Peer reviewed', 4),

('5. Conference', 'Tier 1', 5),
('5. Conference', 'Tier 2', 3),
('5. Conference', 'Tier 3', 2),

('6. Others', 'Paper/Poster Presentation', 2),
('6. Others', 'Book chapter', 3),
('6. Others', 'Book edited', 5),
('6. Others', 'Textbook published', 6),

('7. Sponsored project (approved in AY)', 'Grants received: Value>=20lacs (points for each project for PI)', 15),
('7. Sponsored project (approved in AY)', 'Grants received: Values>=20lacs (points for each project for co-PI)', 7.5),
('7. Sponsored project (approved in AY)', 'Grants received: 10lacs<=value<20lacs (PI)', 12),
('7. Sponsored project (approved in AY)', 'Grants received: 10lacs<=value<20lacs (co-PI)', 6),
('7. Sponsored project (approved in AY)', 'Grants received: 5lacs<=value<10lacs (PI)', 9),
('7. Sponsored project (approved in AY)', 'Grants received: 5lacs<=value<10lacs (co-PI)', 4.5),
('7. Sponsored project (approved in AY)', 'Grants received: 2lacs<=value<5lacs (PI)', 6),
('7. Sponsored project (approved in AY)', 'Grants received: 2lacs<=value<5lacs (co-PI)', 3),
('7. Sponsored project (approved in AY)', 'Grants received: 50000<=value<2lacs (PI)', 3),
('7. Sponsored project (approved in AY)', 'Grants received: 50000<=value<2lacs (co-PI)', 1.5),
('7. Sponsored project (approved in AY)', 'Proposals submitted: Submitted in that AY (PI)', 2),
('7. Sponsored project (approved in AY)', 'Proposals submitted: Submitted in that AY (co-PI)', 1),

('8. Patent', 'Granted in that AY', 10),
('8. Patent', 'Published in that AY', 5),
('8. Patent', 'Filed in that AY', 2.5),

('9. Technology Contribution', 'Technology developed and transferred', 10),
('9. Technology Contribution', 'Software developed and deployed', 2),

('10. Review of research papers', 'Q1,Q2 refereed international research journals (up to a maximum of 10 points)', 1),
('10. Review of research papers', 'Q3,Q4,conference papers (up to a maximum of 10 points)', 0.5),

('11. Talks and conferences', 'Convenor (coordinator)/co-coordinator/organizing chair of workshop/conference/FDP', 5),
('11. Talks and conferences', 'Co-convenor of workshop/conference/FDP', 3),
('11. Talks and conferences', 'Organizing committee member of workshop/conference/FDP', 1),
('11. Talks and conferences', 'Invited talks: FDPs/Conferences (up to a maximum of 10 points)', 2),
('11. Talks and conferences', 'Invited talks: Other invited talks (up to a maximum of 5 points)', 1),
('11. Talks and conferences', 'Conference outside LNMIIT: PC Chair, Session Chair, General Chair', 2),
('11. Talks and conferences', 'Conference outside LNMIIT: TPC member, Other member', 1),

('12. Visits/Honours/Consultancy', 'Visits to other institutions for Research/Industries for Collaborative work (up to a max of 10)', 1),
('12. Visits/Honours/Consultancy', 'International Honours', 10),
('12. Visits/Honours/Consultancy', 'National Honours', 5),
('12. Visits/Honours/Consultancy', 'Consultancy Project: Project Value >5 lacs (PI)', 10),
('12. Visits/Honours/Consultancy', 'Consultancy Project: Project Value >5 lacs (co-PI)', 5),
('12. Visits/Honours/Consultancy', 'Consultancy Project: 2 lacs<=Project Value<=5lacs (PI)', 6),
('12. Visits/Honours/Consultancy', 'Consultancy Project: 2 lacs<=Project Value<=5lacs (co-PI)', 3),
('12. Visits/Honours/Consultancy', 'Consultancy Project: Project value <2 lacs (PI)', 3),
('12. Visits/Honours/Consultancy', 'Consultancy Project: Project value <2 lacs (co-PI)', 1.5),

('13. Other Institutional Contributions', 'Administrative Positions: Dean', 15),
('13. Other Institutional Contributions', 'Administrative Positions: Associate Dean', 10),
('13. Other Institutional Contributions', 'Administrative Positions: Assistant Dean', 5),
('13. Other Institutional Contributions', 'Administrative Positions: HoD', 15),
('13. Other Institutional Contributions', 'Administrative Positions: Chief Warden', 10),
('13. Other Institutional Contributions', 'Administrative Positions: Associate Chief Warden', 7),
('13. Other Institutional Contributions', 'Administrative Positions: Warden', 5),
('13. Other Institutional Contributions', 'Administrative Positions: Assistant Warden', 3),
('13. Other Institutional Contributions', 'Administrative Positions: Centre Lead', 10),
('13. Other Institutional Contributions', 'Administrative Positions: Centre Co-Lead', 5),
('13. Other Institutional Contributions', 'Other Significant: Chairperson of one or more significant committees', 10),
('13. Other Institutional Contributions', 'Other Significant: Convenor of one or more significant committees', 6),
('13. Other Institutional Contributions', 'Other Significant: Committee Member (up to a maximum of 5 points)', 1),
('13. Other Institutional Contributions', 'Other Significant: Faculty Mentor of any Cell (Mentorship)', 2),
('13. Other Institutional Contributions', 'Other Significant: Member of Major responsibilities (Admissions, Accreditations, etc)', 6),
('13. Other Institutional Contributions', 'Other Significant: Conduct of new certificate programmes', 5),
('13. Other Institutional Contributions', 'Other Significant: Scholarly articles in reputed newspapers/magazines (max 9 points)', 3),

('14. Other activities', 'Other activities (up to a maximum of 10 points) [1-3 points]', 3);
